# ============================================================================
# Argo CD Repository Secrets for hello-world App
# ============================================================================
# 
# Apply this after installing Argo CD:
#   kubectl apply -f argocd-repository-secret.yaml
#
# IMPORTANT: Replace <your-argocd-machine-user> with your Argo CD machine username,
# and replace <your-github-token> with an actual GitHub personal 
# access token or deploy key before applying!  
# <i>See: argocd-machine-user-github-token.md</i> 
#
# SECURITY: BE SURE TO DELETE OR EXCLUDE THIS FILE FROM GIT TO PREVENT
# COMMITTING YOUR GITHUB TOKEN(S) TO GITHUB!
#
# Required Permissions for GitHub Token:
#   - repo (Full control of private repositories)
#   - read:packages (Download packages from GitHub Container Registry)
# ============================================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-app-of-apps-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-go-template/hello-world-app-of-apps
  password: <your-github-token>  # DO NOT COMMIT YOUR GITHUB TOKEN(S) TO GITHUB
  username: <your-argocd-machine-user>

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-config-dev-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-go-template/hello-world-config-dev
  password: <your-github-token>  # DO NOT COMMIT YOUR GITHUB TOKEN(S) TO GITHUB
  username: <your-argocd-machine-user>

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-config-qa-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-go-template/hello-world-config-qa
  password: <your-github-token>  # DO NOT COMMIT YOUR GITHUB TOKEN(S) TO GITHUB
  username: <your-argocd-machine-user>

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-config-staging-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-go-template/hello-world-config-staging
  password: <your-github-token>  # DO NOT COMMIT YOUR GITHUB TOKEN(S) TO GITHUB
  username: <your-argocd-machine-user>

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-config-prod-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-go-template/hello-world-config-prod
  password: <your-github-token>  # DO NOT COMMIT YOUR GITHUB TOKEN(S) TO GITHUB
  username: <your-argocd-machine-user>
