# Apply this after installing Argo CD
# kubectl apply -f argocd-repository-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: hello-world-repos
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-go-template/hello-world-apps.git
  password: <your-github-token>
  username: essesseff-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-config-dev-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-go-template/hello-world-config-dev.git
  password: <your-github-token>
  username: essesseff-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-config-qa-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-go-template/hello-world-config-qa.git
  password: <your-github-token>
  username: essesseff-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-config-staging-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-go-template/hello-world-config-staging.git
  password: <your-github-token>
  username: essesseff-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-config-prod-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-go-template/hello-world-config-prod.git
  password: <your-github-token>
  username: essesseff-admin
